spring:
  application:
    name: notion-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ITMO-highload-systems/config.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          default-label: master
          search-paths: "{application}"

server:
  port: ${NOTION_CONFIG_SERVER_PORT:8888}


